# Generated by Django 5.0 on 2023-12-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(db_index=True, max_length=200)),
                ('etykieta', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(db_index=True, max_length=200)),
                ('etykieta', models.SlugField(max_length=200)),
                ('obraz', models.ImageField(blank=True, upload_to='produkty/%Y/%m/%d')),
                ('opis', models.TextField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostepne', models.BooleanField(default=True)),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('aktualizacja', models.DateTimeField(auto_now=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkty', to='sklep.kategoria')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'produkty',
                'ordering': ('nazwa',),
                'index_together': {('id', 'etykieta')},
            },
        ),
    ]
